#Este programa pregunta polos teus favoritos
print('Dime cal e a tua cor favorita')
corFavorita = raw_input()
print('Dime cal e o teu animal favorito')
animalFavorito = raw_input()
print('Dime cal e a tua comida favorita')
comidaFav = raw_input()
print('--------------------')
print('Contestache: '+corFavorita+', '+animalFavorito+', '+comidaFav)
print('--------------------')
print('Cor: '+corFavorita)
print('Animal: '+animalFavorito)
print('Comida: '+comidaFav)
